---
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g markdown-spellcheck write-good
jobs:
  include:
    - script: 'mdspell --ignore-acronyms --en-us --report "content/post/*.md"'
    - script: 'write-good --yes-eprime --parse content/*/*.md || true'
branches:
  only:
    - master    
