---
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g markdown-spellcheck write-good
jobs:
  include:
    - script: 'mdspell --ignore-acronyms --en-us --report "content/*/*.md"'
    - script: 'write-good content/*/*.md'
branches:
  only:
    - master    
