baseurl                  = "https://pawel.krupa.net.pl/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Tech & Photography"
theme                    = "hugo-theme-sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics          = "UA-121689100-1"                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "02 Jan 2006"
    dateformfull         = "02 Jan 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = ""

# Metadata for Open Graph and Twitter
    description          = "Tech & Photography"               # Max 160 characters show in search results
    images               = ["tn.png"]                         # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Pawel on Tech & Photo"

    customCSS = [ "custom.css" ] 

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

#[[params.mainMenu]]
#    link = "/gallery"
#    text = "gallery"

[[params.mainMenu]]
    link = "/talks"
    text = "talks"

[[params.mainMenu]]
    link = "/about"
    text = "who am I?"

[imaging]
    quality = 75
